dotcloud push fawave.url0 .
dotcloud push fawave.url1 .
dotcloud push fawave.url2 .
dotcloud push fawave.url3 .
dotcloud push fawave.url4 .
dotcloud push fawave.url5 .
dotcloud push fawave.url6 .
dotcloud push fawave.url7 .
dotcloud push fawave.url8 .
dotcloud push fawave.url9 .
dotcloud push fawave.url10 .
dotcloud push fawave.url11 .
dotcloud push fawave.url12 .
dotcloud push fawave.url13 .
dotcloud push fawave.url14 .
dotcloud push fawave.url15 .
dotcloud push fawave.url16 .
dotcloud push fawave.url17 .
dotcloud push fawave.url18 .
dotcloud push fawave.url19 .
dotcloud push fawave.url20 .
dotcloud push fawave.url21 .
dotcloud push fawave.url22 .
dotcloud push fawave.url23 .
dotcloud push fawave.url24 .
dotcloud push fawave.url25 .
dotcloud push fawave.url26 .
dotcloud push fawave.url27 .
dotcloud push fawave.url28 .
dotcloud push fawave.url29 .
dotcloud push fawave.url30 .
dotcloud push fawave.url31 .
dotcloud push fawave.url32 .
dotcloud push fawave.url33 .
dotcloud push fawave.url34 .
dotcloud push fawave.url35 .
dotcloud push fawave.url36 .
dotcloud push fawave.url37 .
dotcloud push fawave.url38 .
dotcloud push fawave.url39 .
dotcloud push fawave.url40 .
dotcloud push fawave.url41 .
dotcloud push fawave.url42 .
dotcloud push fawave.url43 .
dotcloud push fawave.url44 .
dotcloud push fawave.url45 .
dotcloud push fawave.url46 .
dotcloud push fawave.url47 .
dotcloud push fawave.url48 .
dotcloud push fawave.url49 .
dotcloud push fawave.url50 .
